version: '3.9'
services:
  app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      -  5000:5000
    volumes:
      - ./harvard:/app/harvard
    command: example1.py
