apiVersion: v1
kind: Service
metadata:
  name: svastikkka-chatbot-service
  labels:
    app: svastikkka-chatbot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8501
  selector:
    app: svastikkka-chatbot
